import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/context/ThemeContext";
import { DrawerModeProvider } from "@/src/context/DrawerModeContext";
import LayoutClient from "@/src/components/layouts/LayoutClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Startup Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <DrawerModeProvider>
            <LayoutClient>
              {children}
            </LayoutClient>
          </DrawerModeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
