import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/context/ThemeContext";
import { DrawerModeProvider } from "@/src/context/DrawerModeContext";
import LayoutClient from "@/src/components/layouts/LayoutClient";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Startup Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${montserrat.variable}`}>
      <body>
        <ThemeProvider>
          <DrawerModeProvider>
            <LayoutClient>
              {children}
            </LayoutClient>
          </DrawerModeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
